

/* ======== BEGIN nnrtld (rtld) =========== */


/* ======== END nnrtld (rtld) ============== */



/* ======== BEGIN EX-King (main) =========== */

{ util::ModuleIndex::Main, 0x01888e6c, "_ZN4sead10TextWriter13setupGraphicsEPNS_11DrawContextE" },
{ util::ModuleIndex::Main, 0x010ad4cc, "_ZN4sead10TextWriter20setCursorFromTopLeftERKNS_7Vector2IfEE" },
{ util::ModuleIndex::Main, 0x018890d4, "_ZN4sead10TextWriter6printfEPKcz" },
{ util::ModuleIndex::Main, 0x010ad510, "_ZN4sead10TextWriterC1EPNS_11DrawContextEPKNS_8ViewportE" },
{ util::ModuleIndex::Main, 0x010ad478, "_ZN4sead10TextWriterD1Ev" },
{ util::ModuleIndex::Main, 0x04716f08, "_ZN4sead12GlobalRandom9sInstanceE" },
{ util::ModuleIndex::Main, 0x04716c08, "_ZN4sead7HeapMgr10sRootHeapsE" },
{ util::ModuleIndex::Main, 0x04716ca0, "_ZN4sead7HeapMgr12sInstancePtrE" },
{ util::ModuleIndex::Main, 0x00e7cdc4, "_ZN4sead7HeapMgr15createRootHeap_Ev" },
{ util::ModuleIndex::Main, 0x0076eb88, "_ZN6engine5actor12BaseProcLinkD2Ev" },
{ util::ModuleIndex::Main, 0x007fe124, "_ZNK4sead7HeapMgr15findContainHeapEPKv" },
{ util::ModuleIndex::Main, 0x00a9123c, "agl::create_arg" },
{ util::ModuleIndex::Main, 0x04716af8, "agl::default_font" },
{ util::ModuleIndex::Main, 0x00a92964, "agl::init_debug_drawers" },
{ util::ModuleIndex::Main, 0x0081911c, "agl::lyr::Layer::drawDebugInfo_" },
{ util::ModuleIndex::Main, 0x00818340, "agl::lyr::RenderDisplay::drawLayer_::ensure_font" },
{ util::ModuleIndex::Main, 0x00bc81ac, "agl::lyr::Renderer::draw" },
{ util::ModuleIndex::Main, 0x02a267bc, "engine::MainGetNpadStates" },
{ util::ModuleIndex::Main, 0x006ba86c, "engine::actor::ActorBase::forceSetMatrix" },
{ util::ModuleIndex::Main, 0x00860020, "engine::actor::ActorBase::setPositionAndRotationDirect" },
{ util::ModuleIndex::Main, 0x00823fd8, "engine::actor::ActorBase::updatePositionAndRotation" },
{ util::ModuleIndex::Main, 0x0117f4a4, "engine::actor::ActorMgr::createActorAndConnectSync" },
{ util::ModuleIndex::Main, 0x012b13dc, "engine::actor::ActorMgr::createActorAndConnectSyncImpl" },
{ util::ModuleIndex::Main, 0x0140cb58, "engine::actor::ActorMgr::createActorAndConnectSync__2" },
{ util::ModuleIndex::Main, 0x00ab92cc, "engine::actor::ActorMgr::requestCreateActorAsync" },
{ util::ModuleIndex::Main, 0x012a8b44, "engine::actor::ActorMgr::requestCreateActorSync" },
{ util::ModuleIndex::Main, 0x04722920, "engine::actor::ActorMgr::sInstance" },
{ util::ModuleIndex::Main, 0x0244a80c, "engine::actor::BaseProcCreateAndDeleteThread::calc_create" },
{ util::ModuleIndex::Main, 0x0244ac40, "engine::actor::BaseProcCreateAndDeleteThread::calc_delete" },
{ util::ModuleIndex::Main, 0x00b7cb84, "engine::actor::BaseProcLink::setProc" },
{ util::ModuleIndex::Main, 0x00d8b0ec, "engine::actor::BaseProcMgr::addDependency" },
{ util::ModuleIndex::Main, 0x008eee60, "engine::actor::BaseProcMgr::removeDependency" },
{ util::ModuleIndex::Main, 0x04722268, "engine::actor::BaseProcMgr::sInstance" },
{ util::ModuleIndex::Main, 0x011f0700, "engine::event::EventMgr::requestEvent" },
{ util::ModuleIndex::Main, 0x047258c8, "engine::event::EventMgr::sInstance" },
{ util::ModuleIndex::Main, 0x04725bb8, "engine::module::VFRMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00e7ac48, "engine::nnMain_post_setup" },
{ util::ModuleIndex::Main, 0x007f61d0, "engine::steal_heap" },
{ util::ModuleIndex::Main, 0x008f2358, "game::actor::GameActor::getComponent<game::component::PlayerComponent>" },
{ util::ModuleIndex::Main, 0x01d76ef4, "game::ai::execute::ExecutePlayerReverseRecorder::updateImpl_::state0" },
{ util::ModuleIndex::Main, 0x01d8feb4, "game::ai::execute::ExecutePlayerWhistle::enterImpl_" },
{ util::ModuleIndex::Main, 0x00cb4474, "game::component::GameCameraParam::HACK_cameraCalc" },
{ util::ModuleIndex::Main, 0x009f98cc, "game::component::PlayerComponent::checkContactMiasma" },
{ util::ModuleIndex::Main, 0x01621cbc, "game::component::PlayerComponent::setLinearVelocity" },
{ util::ModuleIndex::Main, 0x00b36920, "game::wm::WorldManagerModule::baseProcExe" },
{ util::ModuleIndex::Main, 0x0020d98c, "hkUNKNOWN::UNKNOWN_applyMotion" },
{ util::ModuleIndex::Main, 0x00eb8640, "phive::CharacterMatterRigidBodyEntity::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x008aa374, "phive::ControllerSet::visitRigidBodyEntities" },
{ util::ModuleIndex::Main, 0x00cf600c, "phive::RigidBodyBase::applyLinearImpulse" },
{ util::ModuleIndex::Main, 0x00b7d5d4, "phive::RigidBodyBase::getAABB" },
{ util::ModuleIndex::Main, 0x00a3c1c4, "phive::RigidBodyBase::getBoundingBoxWorld" },
{ util::ModuleIndex::Main, 0x02a911b8, "phive::RigidBodyBase::getName" },
{ util::ModuleIndex::Main, 0x011b44ac, "phive::RigidBodyBase::getNextLinearVelocity" },
{ util::ModuleIndex::Main, 0x00acc874, "phive::RigidBodyBase::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x00fce23c, "phive::RigidBodyEntity::getActorLink" },
{ util::ModuleIndex::Main, 0x00ac2bfc, "sead::FrameHeap::create" },
{ util::ModuleIndex::Main, 0x00a2e4b0, "sead::LookAtCamera::doUpdateMatrix" },
{ util::ModuleIndex::Main, 0x022707c8, "sead::PrimitiveDrawer::begin" },
{ util::ModuleIndex::Main, 0x02270904, "sead::PrimitiveDrawer::drawBox" },
{ util::ModuleIndex::Main, 0x021c3b20, "sead::PrimitiveDrawer::drawCircle32" },
{ util::ModuleIndex::Main, 0x021c3bac, "sead::PrimitiveDrawer::drawCylinder16" },
{ util::ModuleIndex::Main, 0x021c3c48, "sead::PrimitiveDrawer::drawCylinder32" },
{ util::ModuleIndex::Main, 0x021c3a7c, "sead::PrimitiveDrawer::drawDisk32" },
{ util::ModuleIndex::Main, 0x021c37bc, "sead::PrimitiveDrawer::drawLine" },
{ util::ModuleIndex::Main, 0x021c3654, "sead::PrimitiveDrawer::drawQuad" },
{ util::ModuleIndex::Main, 0x022708d8, "sead::PrimitiveDrawer::drawQuad2" },
{ util::ModuleIndex::Main, 0x021c393c, "sead::PrimitiveDrawer::drawSphere4x8" },
{ util::ModuleIndex::Main, 0x021c39d8, "sead::PrimitiveDrawer::drawSphere8x16" },
{ util::ModuleIndex::Main, 0x021c372c, "sead::PrimitiveDrawer::drawWireCube" },
{ util::ModuleIndex::Main, 0x022707f0, "sead::PrimitiveDrawer::end" },
{ util::ModuleIndex::Main, 0x0227010c, "sead::PrimitiveDrawer::setCamera" },
{ util::ModuleIndex::Main, 0x022707c0, "sead::PrimitiveDrawer::setDrawCtx" },
{ util::ModuleIndex::Main, 0x02270118, "sead::PrimitiveDrawer::setModelMtx" },
{ util::ModuleIndex::Main, 0x021c362c, "sead::PrimitiveDrawer::setProjection" },
{ util::ModuleIndex::Main, 0x04718c80, "sead::PrimitiveRenderer::instance" },
{ util::ModuleIndex::Main, 0x010f1c6c, "sead::Random::getU32" },
{ util::ModuleIndex::Main, 0x04716e00, "sead::ThreadMgr::sInstance" },

/* ======== END EX-King (main) ============== */



/* ======== BEGIN multimedia (subsdk0) =========== */


/* ======== END multimedia (subsdk0) ============== */



/* ======== BEGIN nnSdk (sdk) =========== */


/* ======== END nnSdk (sdk) ============== */

{ util::ModuleIndex::Main, 0x0, "__null_unused__" }
