

/* ======== BEGIN nnrtld (rtld) =========== */


/* ======== END nnrtld (rtld) ============== */



/* ======== BEGIN EX-King (main) =========== */

{ util::ModuleIndex::Main, 0x0188e060, "_ZN4sead10TextWriter13setupGraphicsEPNS_11DrawContextE" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead10TextWriter20setCursorFromTopLeftERKNS_7Vector2IfEE" },
{ util::ModuleIndex::Main, 0x0188e2c8, "_ZN4sead10TextWriter6printfEPKcz" },
{ util::ModuleIndex::Main, 0x010b4648, "_ZN4sead10TextWriterC1EPNS_11DrawContextEPKNS_8ViewportE" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead10TextWriterD1Ev" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead12GlobalRandom9sInstanceE" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead7HeapMgr10sRootHeapsE" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead7HeapMgr12sInstancePtrE" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN4sead7HeapMgr15createRootHeap_Ev" },
{ util::ModuleIndex::Main, 0x00000000, "_ZN6engine5actor12BaseProcLinkD2Ev" },
{ util::ModuleIndex::Main, 0x00000000, "_ZNK4sead7HeapMgr15findContainHeapEPKv" },
{ util::ModuleIndex::Main, 0x00a9c6b4, "agl::create_arg" },
{ util::ModuleIndex::Main, 0x04713a28, "agl::default_font" },
{ util::ModuleIndex::Main, 0x00a9dddc, "agl::init_debug_drawers" },
{ util::ModuleIndex::Main, 0x00808efc, "agl::lyr::Layer::drawDebugInfo_" },
{ util::ModuleIndex::Main, 0x00808478, "agl::lyr::RenderDisplay::drawLayer_::ensure_font" },
{ util::ModuleIndex::Main, 0x00000000, "agl::lyr::Renderer::draw" },
{ util::ModuleIndex::Main, 0x00000000, "engine::MainGetNpadStates" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorBase::forceSetMatrix" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorBase::setPositionAndRotationDirect" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorBase::updatePositionAndRotation" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::createActorAndConnectSync" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::createActorAndConnectSyncImpl" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::createActorAndConnectSync__2" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::requestCreateActorAsync" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::requestCreateActorSync" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::ActorMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::BaseProcCreateAndDeleteThread::calc_create" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::BaseProcCreateAndDeleteThread::calc_delete" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::BaseProcLink::setProc" },
{ util::ModuleIndex::Main, 0x00d9fc2c, "engine::actor::BaseProcMgr::addDependency" },
{ util::ModuleIndex::Main, 0x008b6e90, "engine::actor::BaseProcMgr::removeDependency" },
{ util::ModuleIndex::Main, 0x00000000, "engine::actor::BaseProcMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00000000, "engine::event::EventMgr::requestEvent" },
{ util::ModuleIndex::Main, 0x00000000, "engine::event::EventMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00803b40, "engine::module::PauseMgr::initialize" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::PauseMgr::processRequests" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::PauseMgr::processRequests_inlineModuleCalc" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::PauseMgr::processRequests_withQueryIsTargetPaused" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::PauseMgr::releasePause" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::PauseMgr::requestPause" },
{ util::ModuleIndex::Main, 0x00000000, "engine::module::VFRMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00000000, "engine::nnMain_post_setup" },
{ util::ModuleIndex::Main, 0x00802bfc, "engine::steal_heap" },
{ util::ModuleIndex::Main, 0x00000000, "engine::util::HashMurmur32" },
{ util::ModuleIndex::Main, 0x00000000, "game::actor::GameActor::getComponent<game::component::PlayerComponent>" },
{ util::ModuleIndex::Main, 0x00000000, "game::ai::execute::ExecutePlayerReverseRecorder::updateImpl_::state0" },
{ util::ModuleIndex::Main, 0x00000000, "game::ai::execute::ExecutePlayerWhistle::enterImpl_" },
{ util::ModuleIndex::Main, 0x00000000, "game::component::GameCameraParam::HACK_cameraCalc" },
{ util::ModuleIndex::Main, 0x00000000, "game::component::PlayerComponent::checkContactMiasma" },
{ util::ModuleIndex::Main, 0x00000000, "game::component::PlayerComponent::setLinearVelocity" },
{ util::ModuleIndex::Main, 0x00ae0848, "game::wm::WorldManagerModule::baseProcExe" },
{ util::ModuleIndex::Main, 0x0020d98c, "hkUNKNOWN::UNKNOWN_applyMotion" },
{ util::ModuleIndex::Main, 0x00000000, "phive::CharacterMatterRigidBodyEntity::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x00000000, "phive::ControllerSet::visitRigidBodyEntities" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::applyLinearImpulse" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::getAABB" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::getBoundingBoxWorld" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::getName" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::getNextLinearVelocity" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyBase::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x00000000, "phive::RigidBodyEntity::getActorLink" },
{ util::ModuleIndex::Main, 0x00000000, "sead::FrameHeap::create" },
{ util::ModuleIndex::Main, 0x00000000, "sead::LookAtCamera::doUpdateMatrix" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::begin" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawBox" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawCircle32" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawCylinder16" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawCylinder32" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawDisk32" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawLine" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawQuad" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawQuad2" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawSphere4x8" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawSphere8x16" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::drawWireCube" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::end" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::setCamera" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::setDrawCtx" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::setModelMtx" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveDrawer::setProjection" },
{ util::ModuleIndex::Main, 0x00000000, "sead::PrimitiveRenderer::instance" },
{ util::ModuleIndex::Main, 0x00000000, "sead::Random::getU32" },
{ util::ModuleIndex::Main, 0x00000000, "sead::ThreadMgr::sInstance" },

/* ======== END EX-King (main) ============== */



/* ======== BEGIN multimedia (subsdk0) =========== */


/* ======== END multimedia (subsdk0) ============== */



/* ======== BEGIN nnSdk (sdk) =========== */


/* ======== END nnSdk (sdk) ============== */

{ util::ModuleIndex::Main, 0x0, "__null_unused__" }
