

/* ======== BEGIN nnrtld (rtld) =========== */


/* ======== END nnrtld (rtld) ============== */



/* ======== BEGIN EX-King (main) =========== */

{ util::ModuleIndex::Main, 0x0184c778, "_ZN4sead10TextWriter13setupGraphicsEPNS_11DrawContextE" },
{ util::ModuleIndex::Main, 0x0108ecd8, "_ZN4sead10TextWriter20setCursorFromTopLeftERKNS_7Vector2IfEE" },
{ util::ModuleIndex::Main, 0x0184c9e0, "_ZN4sead10TextWriter6printfEPKcz" },
{ util::ModuleIndex::Main, 0x0108ed1c, "_ZN4sead10TextWriterC1EPNS_11DrawContextEPKNS_8ViewportE" },
{ util::ModuleIndex::Main, 0x029bc880, "_ZN4sead10TextWriterD1Ev" },
{ util::ModuleIndex::Main, 0x0463c108, "_ZN4sead12GlobalRandom9sInstanceE" },
{ util::ModuleIndex::Main, 0x0463be08, "_ZN4sead7HeapMgr10sRootHeapsE" },
{ util::ModuleIndex::Main, 0x0463bea0, "_ZN4sead7HeapMgr12sInstancePtrE" },
{ util::ModuleIndex::Main, 0x00e9b7bc, "_ZN4sead7HeapMgr15createRootHeap_Ev" },
{ util::ModuleIndex::Main, 0x009665d0, "_ZN6engine5actor12BaseProcLinkD2Ev" },
{ util::ModuleIndex::Main, 0x00783ac4, "_ZNK4sead7HeapMgr15findContainHeapEPKv" },
{ util::ModuleIndex::Main, 0x00ea5118, "agl::create_arg" },
{ util::ModuleIndex::Main, 0x0463c0f8, "agl::default_font" },
{ util::ModuleIndex::Main, 0x00ea6834, "agl::init_debug_drawers" },
{ util::ModuleIndex::Main, 0x00858998, "agl::lyr::Layer::drawDebugInfo_" },
{ util::ModuleIndex::Main, 0x00857f28, "agl::lyr::RenderDisplay::drawLayer_::ensure_font" },
{ util::ModuleIndex::Main, 0x00b983b4, "agl::lyr::Renderer::draw" },
{ util::ModuleIndex::Main, 0x029b442c, "engine::MainGetNpadStates" },
{ util::ModuleIndex::Main, 0x0069a18c, "engine::actor::ActorBase::forceSetMatrix" },
{ util::ModuleIndex::Main, 0x007f13c0, "engine::actor::ActorBase::setPositionAndRotationDirect" },
{ util::ModuleIndex::Main, 0x007b76b8, "engine::actor::ActorBase::updatePositionAndRotation" },
{ util::ModuleIndex::Main, 0x010c6838, "engine::actor::ActorMgr::createActorAndConnectSync" },
{ util::ModuleIndex::Main, 0x01293710, "engine::actor::ActorMgr::createActorAndConnectSyncImpl" },
{ util::ModuleIndex::Main, 0x013e2d68, "engine::actor::ActorMgr::createActorAndConnectSync__2" },
{ util::ModuleIndex::Main, 0x00a5fdf8, "engine::actor::ActorMgr::requestCreateActorAsync" },
{ util::ModuleIndex::Main, 0x01278724, "engine::actor::ActorMgr::requestCreateActorSync" },
{ util::ModuleIndex::Main, 0x046479e0, "engine::actor::ActorMgr::sInstance" },
{ util::ModuleIndex::Main, 0x023c7e94, "engine::actor::BaseProcCreateAndDeleteThread::calc_create" },
{ util::ModuleIndex::Main, 0x023c8248, "engine::actor::BaseProcCreateAndDeleteThread::calc_delete" },
{ util::ModuleIndex::Main, 0x00703440, "engine::actor::BaseProcLink::setProc" },
{ util::ModuleIndex::Main, 0x023c72a0, "engine::actor::BaseProcMgr::addDependency" },
{ util::ModuleIndex::Main, 0x00ab8610, "engine::actor::BaseProcMgr::removeDependency" },
{ util::ModuleIndex::Main, 0x04647330, "engine::actor::BaseProcMgr::sInstance" },
{ util::ModuleIndex::Main, 0x011e5300, "engine::event::EventMgr::requestEvent" },
{ util::ModuleIndex::Main, 0x0464a988, "engine::event::EventMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00f56800, "engine::module::PauseMgr::releasePause" },
{ util::ModuleIndex::Main, 0x01092294, "engine::module::PauseMgr::requestPause" },
{ util::ModuleIndex::Main, 0x04661598, "engine::module::VFRMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00e998b8, "engine::nnMain_post_setup" },
{ util::ModuleIndex::Main, 0x008111a8, "engine::steal_heap" },
{ util::ModuleIndex::Main, 0x00812140, "engine::system::PauseMgr::initialize" },
{ util::ModuleIndex::Main, 0x006feea8, "engine::util::HashMurmur32" },
{ util::ModuleIndex::Main, 0x008ce618, "game::actor::GameActor::getComponent<game::component::PlayerComponent>" },
{ util::ModuleIndex::Main, 0x01d151a0, "game::ai::execute::ExecutePlayerReverseRecorder::updateImpl_::state0" },
{ util::ModuleIndex::Main, 0x01d2e1c4, "game::ai::execute::ExecutePlayerWhistle::enterImpl_" },
{ util::ModuleIndex::Main, 0x00c7de84, "game::component::GameCameraParam::HACK_cameraCalc" },
{ util::ModuleIndex::Main, 0x00975c20, "game::component::PlayerComponent::checkContactMiasma" },
{ util::ModuleIndex::Main, 0x015ebbfc, "game::component::PlayerComponent::setLinearVelocity" },
{ util::ModuleIndex::Main, 0x00b22a34, "game::wm::WorldManagerModule::baseProcExe" },
{ util::ModuleIndex::Main, 0x0022ed04, "hkUNKNOWN::UNKNOWN_applyMotion" },
{ util::ModuleIndex::Main, 0x00ebe224, "phive::CharacterMatterRigidBodyEntity::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x008d6b30, "phive::ControllerSet::visitRigidBodyEntities" },
{ util::ModuleIndex::Main, 0x00c2bd7c, "phive::RigidBodyBase::applyLinearImpulse" },
{ util::ModuleIndex::Main, 0x007c1834, "phive::RigidBodyBase::getAABB" },
{ util::ModuleIndex::Main, 0x009865d0, "phive::RigidBodyBase::getBoundingBoxWorld" },
{ util::ModuleIndex::Main, 0x02a1e9e4, "phive::RigidBodyBase::getName" },
{ util::ModuleIndex::Main, 0x011613d0, "phive::RigidBodyBase::getNextLinearVelocity" },
{ util::ModuleIndex::Main, 0x00661dc0, "phive::RigidBodyBase::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x0069cc14, "phive::RigidBodyEntity::getActorLink" },
{ util::ModuleIndex::Main, 0x00b111dc, "sead::FrameHeap::create" },
{ util::ModuleIndex::Main, 0x00a15d40, "sead::LookAtCamera::doUpdateMatrix" },
{ util::ModuleIndex::Main, 0x021f74f8, "sead::PrimitiveDrawer::begin" },
{ util::ModuleIndex::Main, 0x021f7634, "sead::PrimitiveDrawer::drawBox" },
{ util::ModuleIndex::Main, 0x0214f0c0, "sead::PrimitiveDrawer::drawCircle32" },
{ util::ModuleIndex::Main, 0x0214f14c, "sead::PrimitiveDrawer::drawCylinder16" },
{ util::ModuleIndex::Main, 0x0214f1e8, "sead::PrimitiveDrawer::drawCylinder32" },
{ util::ModuleIndex::Main, 0x0214f01c, "sead::PrimitiveDrawer::drawDisk32" },
{ util::ModuleIndex::Main, 0x0214ed5c, "sead::PrimitiveDrawer::drawLine" },
{ util::ModuleIndex::Main, 0x0214ebf4, "sead::PrimitiveDrawer::drawQuad" },
{ util::ModuleIndex::Main, 0x021f7608, "sead::PrimitiveDrawer::drawQuad2" },
{ util::ModuleIndex::Main, 0x0214eedc, "sead::PrimitiveDrawer::drawSphere4x8" },
{ util::ModuleIndex::Main, 0x0214ef78, "sead::PrimitiveDrawer::drawSphere8x16" },
{ util::ModuleIndex::Main, 0x0214eccc, "sead::PrimitiveDrawer::drawWireCube" },
{ util::ModuleIndex::Main, 0x021f7520, "sead::PrimitiveDrawer::end" },
{ util::ModuleIndex::Main, 0x021f6e3c, "sead::PrimitiveDrawer::setCamera" },
{ util::ModuleIndex::Main, 0x021f74f0, "sead::PrimitiveDrawer::setDrawCtx" },
{ util::ModuleIndex::Main, 0x021f6e48, "sead::PrimitiveDrawer::setModelMtx" },
{ util::ModuleIndex::Main, 0x0214ebcc, "sead::PrimitiveDrawer::setProjection" },
{ util::ModuleIndex::Main, 0x0463de50, "sead::PrimitiveRenderer::instance" },
{ util::ModuleIndex::Main, 0x010df518, "sead::Random::getU32" },
{ util::ModuleIndex::Main, 0x0463c000, "sead::ThreadMgr::sInstance" },

/* ======== END EX-King (main) ============== */



/* ======== BEGIN multimedia (subsdk0) =========== */


/* ======== END multimedia (subsdk0) ============== */



/* ======== BEGIN nnSdk (sdk) =========== */


/* ======== END nnSdk (sdk) ============== */

{ util::ModuleIndex::Main, 0x0, "__null_unused__" }
