__game_version = 110; /* TOTK_110 */

/* ======== BEGIN EX-King (nso main, symbol __main_start) =========== */

_ZN4game2wm18WorldManagerModule11baseProcExeEPvS2_ = __main_start +         0x00af225c; /* game::wm::WorldManagerModule::baseProcExe(void*, void*) */

/* ======== END   EX-King (nso main) ================================ */



/* ======== BEGIN nnSdk (nso sdk, symbol __sdk_start) =========== */


/* ======== END   nnSdk (nso sdk) ================================ */

