__game_version = 112; /* TOTK_112 */

/* ======== BEGIN EX-King (nso main, symbol __main_start) =========== */

_ZN4sead6Random4TESTEv           = __main_start +         0x00000000; /* sead::Random::TEST() */

/* ======== END   EX-King (nso main) ================================ */



/* ======== BEGIN nnSdk (nso sdk, symbol __sdk_start) =========== */


/* ======== END   nnSdk (nso sdk) ================================ */

