

/* ======== BEGIN nnrtld (rtld) =========== */


/* ======== END nnrtld (rtld) ============== */



/* ======== BEGIN EX-King (main) =========== */

{ util::ModuleIndex::Main, 0x0189917c, "_ZN4sead10TextWriter13setupGraphicsEPNS_11DrawContextE" },
{ util::ModuleIndex::Main, 0x010bfdb4, "_ZN4sead10TextWriter20setCursorFromTopLeftERKNS_7Vector2IfEE" },
{ util::ModuleIndex::Main, 0x018993e4, "_ZN4sead10TextWriter6printfEPKcz" },
{ util::ModuleIndex::Main, 0x010bfdf8, "_ZN4sead10TextWriterC1EPNS_11DrawContextEPKNS_8ViewportE" },
{ util::ModuleIndex::Main, 0x010bfd60, "_ZN4sead10TextWriterD1Ev" },
{ util::ModuleIndex::Main, 0x04719628, "_ZN4sead12GlobalRandom9sInstanceE" },
{ util::ModuleIndex::Main, 0x04719328, "_ZN4sead7HeapMgr10sRootHeapsE" },
{ util::ModuleIndex::Main, 0x047193c0, "_ZN4sead7HeapMgr12sInstancePtrE" },
{ util::ModuleIndex::Main, 0x00ebb084, "_ZN4sead7HeapMgr15createRootHeap_Ev" },
{ util::ModuleIndex::Main, 0x007f6180, "_ZN6engine5actor12BaseProcLinkD2Ev" },
{ util::ModuleIndex::Main, 0x007612b0, "_ZNK4sead7HeapMgr15findContainHeapEPKv" },
{ util::ModuleIndex::Main, 0x00adb7cc, "agl::create_arg" },
{ util::ModuleIndex::Main, 0x04719618, "agl::default_font" },
{ util::ModuleIndex::Main, 0x00adcef4, "agl::init_debug_drawers" },
{ util::ModuleIndex::Main, 0x0084002c, "agl::lyr::Layer::drawDebugInfo_" },
{ util::ModuleIndex::Main, 0x0083f5b8, "agl::lyr::RenderDisplay::drawLayer_::ensure_font" },
{ util::ModuleIndex::Main, 0x00be8138, "agl::lyr::Renderer::draw" },
{ util::ModuleIndex::Main, 0x02a2c49c, "engine::MainGetNpadStates" },
{ util::ModuleIndex::Main, 0x0070e204, "engine::actor::ActorBase::forceSetMatrix" },
{ util::ModuleIndex::Main, 0x00ec0718, "engine::actor::ActorBase::getRigidBodyEntityByName" },
{ util::ModuleIndex::Main, 0x00a2e240, "engine::actor::ActorBase::setPositionAndRotationDirect" },
{ util::ModuleIndex::Main, 0x009f1924, "engine::actor::ActorBase::updatePositionAndRotation" },
{ util::ModuleIndex::Main, 0x01181d94, "engine::actor::ActorMgr::createActorAndConnectSync" },
{ util::ModuleIndex::Main, 0x012c3514, "engine::actor::ActorMgr::createActorAndConnectSyncImpl" },
{ util::ModuleIndex::Main, 0x014204a4, "engine::actor::ActorMgr::createActorAndConnectSync__2" },
{ util::ModuleIndex::Main, 0x00bde0ac, "engine::actor::ActorMgr::requestCreateActorAsync" },
{ util::ModuleIndex::Main, 0x012ba6c4, "engine::actor::ActorMgr::requestCreateActorSync" },
{ util::ModuleIndex::Main, 0x04725040, "engine::actor::ActorMgr::sInstance" },
{ util::ModuleIndex::Main, 0x02450b8c, "engine::actor::BaseProcCreateAndDeleteThread::calc_create" },
{ util::ModuleIndex::Main, 0x02450f88, "engine::actor::BaseProcCreateAndDeleteThread::calc_delete" },
{ util::ModuleIndex::Main, 0x007ccee8, "engine::actor::BaseProcLink::setProc" },
{ util::ModuleIndex::Main, 0x00dc9360, "engine::actor::BaseProcMgr::addDependency" },
{ util::ModuleIndex::Main, 0x008a6c80, "engine::actor::BaseProcMgr::removeDependency" },
{ util::ModuleIndex::Main, 0x04724988, "engine::actor::BaseProcMgr::sInstance" },
{ util::ModuleIndex::Main, 0x011f6fcc, "engine::event::EventMgr::requestEvent" },
{ util::ModuleIndex::Main, 0x04727fe8, "engine::event::EventMgr::sInstance" },
{ util::ModuleIndex::Main, 0x0083d238, "engine::module::PauseMgr::initialize" },
{ util::ModuleIndex::Main, 0x0083432c, "engine::module::PauseMgr::processRequests" },
{ util::ModuleIndex::Main, 0x008331a8, "engine::module::PauseMgr::processRequests_inlineModuleCalc" },
{ util::ModuleIndex::Main, 0x008fe918, "engine::module::PauseMgr::processRequests_withQueryIsTargetPaused" },
{ util::ModuleIndex::Main, 0x00f832d0, "engine::module::PauseMgr::releasePause" },
{ util::ModuleIndex::Main, 0x0104fdf8, "engine::module::PauseMgr::requestPause" },
{ util::ModuleIndex::Main, 0x047282d8, "engine::module::VFRMgr::sInstance" },
{ util::ModuleIndex::Main, 0x00eb8f08, "engine::nnMain_post_setup" },
{ util::ModuleIndex::Main, 0x0083c2fc, "engine::steal_heap" },
{ util::ModuleIndex::Main, 0x006912cc, "engine::util::HashMurmur32" },
{ util::ModuleIndex::Main, 0x008c165c, "game::actor::GameActor::getComponent<game::component::PlayerComponent>" },
{ util::ModuleIndex::Main, 0x01d84040, "game::ai::execute::ExecutePlayerReverseRecorder::updateImpl_::state0" },
{ util::ModuleIndex::Main, 0x01d9d014, "game::ai::execute::ExecutePlayerWhistle::enterImpl_" },
{ util::ModuleIndex::Main, 0x00cdb894, "game::component::GameCameraParam::HACK_cameraCalc" },
{ util::ModuleIndex::Main, 0x00803640, "game::component::PlayerComponent::checkContactMiasma" },
{ util::ModuleIndex::Main, 0x0163066c, "game::component::PlayerComponent::setLinearVelocity" },
{ util::ModuleIndex::Main, 0x00af225c, "game::wm::WorldManagerModule::baseProcExe" },
{ util::ModuleIndex::Main, 0x0096a528, "game::wm::WorldManagerModule::fogDisable_HACK" },
{ util::ModuleIndex::Main, 0x046d06f8, "game::wm::WorldManagerModule::sInstance" },
{ util::ModuleIndex::Main, 0x01f5d164, "game::wm::WorldManagerModule::setFogDensity" },
{ util::ModuleIndex::Main, 0x01e18ec8, "game::wm::WorldManagerModule::setTime" },
{ util::ModuleIndex::Main, 0x01e18f38, "game::wm::WorldManagerModule::setWeather" },
{ util::ModuleIndex::Main, 0x01e18528, "game::wm::WorldManagerModule::setWind" },
{ util::ModuleIndex::Main, 0x0020d98c, "hkUNKNOWN::UNKNOWN_applyMotion" },
{ util::ModuleIndex::Main, 0x00ee04dc, "phive::CharacterMatterRigidBodyEntity::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x007baa9c, "phive::ControllerSet::visitRigidBodyEntities" },
{ util::ModuleIndex::Main, 0x00ccc234, "phive::RigidBodyBase::applyLinearImpulse" },
{ util::ModuleIndex::Main, 0x00c2c050, "phive::RigidBodyBase::getAABB" },
{ util::ModuleIndex::Main, 0x00c2c050, "phive::RigidBodyBase::getBoundingBoxWorld" },
{ util::ModuleIndex::Main, 0x02a9750c, "phive::RigidBodyBase::getName" },
{ util::ModuleIndex::Main, 0x011bb3b8, "phive::RigidBodyBase::getNextLinearVelocity" },
{ util::ModuleIndex::Main, 0x007a4cfc, "phive::RigidBodyBase::requestSetLinearVelocity" },
{ util::ModuleIndex::Main, 0x006ee2f8, "phive::RigidBodyEntity::getActorLink" },
{ util::ModuleIndex::Main, 0x00b51918, "sead::FrameHeap::create" },
{ util::ModuleIndex::Main, 0x00a8b40c, "sead::LookAtCamera::doUpdateMatrix" },
{ util::ModuleIndex::Main, 0x022787f8, "sead::PrimitiveDrawer::begin" },
{ util::ModuleIndex::Main, 0x02278934, "sead::PrimitiveDrawer::drawBox" },
{ util::ModuleIndex::Main, 0x021ce210, "sead::PrimitiveDrawer::drawCircle32" },
{ util::ModuleIndex::Main, 0x021ce29c, "sead::PrimitiveDrawer::drawCylinder16" },
{ util::ModuleIndex::Main, 0x021ce338, "sead::PrimitiveDrawer::drawCylinder32" },
{ util::ModuleIndex::Main, 0x021ce16c, "sead::PrimitiveDrawer::drawDisk32" },
{ util::ModuleIndex::Main, 0x021cdeac, "sead::PrimitiveDrawer::drawLine" },
{ util::ModuleIndex::Main, 0x021cdd44, "sead::PrimitiveDrawer::drawQuad" },
{ util::ModuleIndex::Main, 0x02278908, "sead::PrimitiveDrawer::drawQuad2" },
{ util::ModuleIndex::Main, 0x021ce02c, "sead::PrimitiveDrawer::drawSphere4x8" },
{ util::ModuleIndex::Main, 0x021ce0c8, "sead::PrimitiveDrawer::drawSphere8x16" },
{ util::ModuleIndex::Main, 0x021cde1c, "sead::PrimitiveDrawer::drawWireCube" },
{ util::ModuleIndex::Main, 0x02278820, "sead::PrimitiveDrawer::end" },
{ util::ModuleIndex::Main, 0x0227813c, "sead::PrimitiveDrawer::setCamera" },
{ util::ModuleIndex::Main, 0x022787f0, "sead::PrimitiveDrawer::setDrawCtx" },
{ util::ModuleIndex::Main, 0x02278148, "sead::PrimitiveDrawer::setModelMtx" },
{ util::ModuleIndex::Main, 0x021cdd1c, "sead::PrimitiveDrawer::setProjection" },
{ util::ModuleIndex::Main, 0x0471b3a0, "sead::PrimitiveRenderer::instance" },
{ util::ModuleIndex::Main, 0x011095ac, "sead::Random::getU32" },
{ util::ModuleIndex::Main, 0x04719520, "sead::ThreadMgr::sInstance" },

/* ======== END EX-King (main) ============== */



/* ======== BEGIN multimedia (subsdk0) =========== */


/* ======== END multimedia (subsdk0) ============== */



/* ======== BEGIN nnSdk (sdk) =========== */


/* ======== END nnSdk (sdk) ============== */

{ util::ModuleIndex::Main, 0x0, "__null_unused__" }
