__game_version = 112; /* TOTK_112 */

/* ======== BEGIN EX-King (nso main, symbol __main_start) =========== */

_ZN4game2wm18WorldManagerModule11baseProcExeEPvS2_ = __main_start +         0x00ae0848; /* game::wm::WorldManagerModule::baseProcExe(void*, void*) */

/* ======== END   EX-King (nso main) ================================ */



/* ======== BEGIN nnSdk (nso sdk, symbol __sdk_start) =========== */


/* ======== END   nnSdk (nso sdk) ================================ */

